css/urls.py
from django.urls import path
from . import views
app_name='css'

urlpatterns = [
    path ('master/',views.get_master, name="master"),
    path('home/',views.get_home, name="home"),
    path('courses/',views.get_courses, name="courses"),
    path('contact/',views.get_contact, name="contact")
]

work/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('css/', include('css.urls'))
]

css/models.py
from django.db import models

# Create your models here.

css/views.py
from django.shortcuts import render

# Create your views here.
def get_master(request):
    return render(request,"css/master.html")

def get_home(request):
    return render(request,"css/home.html")

def get_courses(request):
    return render(request,"css/courses.html")

def get_contact(request):
    return render(request,"css/contact.html")

css/templates/css/contact.html
{% extends 'css/master.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/contact.css' %}">
{%endblock %}


{% block content %}

<br>
<table border="1" cellpadding="3" align="center">
    <tr>
        <th colspan="2">Contact us</th>
    </tr>
    <tr>
        <td>Name</td>
        <td><input type="text"></td>
    </tr>
    <tr>
        <td>Gender</td>
        <td><input type="radio" name="" id="gender">Male
        <input type="radio" name="" id="gender">Female</td>
    </tr>
    <tr>
        <td>Date of birth</td>
        <td><input type="date" name="" id=""></td>
    </tr>
    <tr>
        <td>Mobile</td>
        <td><input type="number" name="" id="mobile"></td>
    </tr>
    <tr>
        <td>Email</td>
        <td><input type="email" name="" id="email"></td>
    </tr>
    <tr>
        <td>Address</td>
        <td><textarea name="" id="" cols="30" rows="5"></textarea></td>
    </tr>
    <tr>
        <td colspan="2" align="right"><a href="#" class="btn">Submit</a></td>
    </tr>

</table>
{% endblock %}

css/templates/css/courses.html
{% extends 'css/master.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'style/courses.css' %}">



{% block content %}

<div id="paradiv">
    <h2>Explore our internship program</h2>
    <p id="para" style="font-size: large;">baabtra.com offers you courses and training programs that will enable you to master programming in depth. Enroll and start learning with the experts in the industry.
        We <br> offer PHP Training with Laravel Framework, Python training with Django Framework, Angular Training and Node.js Training.

    </p><br>

</div>
 <div class="grid-container1">
    <div class="item" style="width: 280px;">
        <img src="{% static 'images/python.jpg' %}" alt="" class="course_image"><h3 align=center>Python Full stack developement</h3></div>
    <div class="item" style="width: 280px;"><img src="{% static 'images/php.png' %}" alt="" class="course_image"><h3 align=center>PHP Full Stack Developement</h3></div>
    <div class="item" style="width: 280px;"><img src="{% static 'images/angular.png' %}" alt="" class="course_image"><h3 align=center>Angular- Front End developement</h3></div>

 </div>

{% endblock %}

css/templates/css/home.html
{% extends 'css/master.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'style/home.css' %}">




{% block content %}
<div>
    <img src="{% static 'images/banner.jpg' %}" alt="" width="100%">
</div>

<div class="content_head">
    <h1 align="center">GETTING A SOFTWARE JOB IS SO EASY WITH OUR <br>INTERNSHIP PROGRAM <br></h1>
   <h1 style="color: #003651;">sdfghxcvbnnm,n</h1>
</div><br>

<div class="grid-container">
    <div class="grid-item"><h3 align="center">Our office</h3><img src="{% static 'images/office.jpg' %}" alt="" width="250px"></div>
    <div class="grid-item">
        <h3 align="center">Best python training in Calicut</h3>
        <p>python is one of the hot programming languages nowadays.
            Many freshers sre learning this software developement technology and
            are getting placed as Python developer in software companies. Baabtra has the 
            highest number of candidates got trained in Python in the last year.
            We train you to develop a web application using python with Django framework and Mysql database.
            Python training course for freshers to make them good programes through quality training in Python and Django framework in Calicut.

        </p>
        
    </div>
    <div class="grid-item">
        <h3 align="center">Life@baabtra</h3>
        <img src="{% static 'images/life.jpg' %}" alt="">
    </div>

</div>



{% endblock %}

css/templates/css/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>baabtra</title>
    <link rel="stylesheet" href="{% static 'style/master.css' %}">
    
    <style>
        p{
            padding: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="{% static 'images/logo.png' %}" alt="" width="200px" height="50px">
        <div style="float: right;">
        <img src="{% static 'images/login.jpg' %}" alt="" width="175px" height="50px">
        <img src="{% static 'images/register.jpg' %}" alt="" width="175px" height="50px">
    </div>
    </div>


    <div class="topnav">
        <a class="active" href="{% url 'css:home' %}">Home</a>
        <a href="{% url 'css:courses' %}">Courses</a>
        <a href="{% url 'css:contact' %}">Contact us</a>
    </div>

    <div class="content">
        {% block content %}


        {% endblock %}
    </div>

    <br>
    <br>

    <div class="footer">
        <table style="width: 100%;border: 1px none black;">
            <tr>
            <td style="border: 1px none black;"><p>baabtra<br>Mentoring partner</p></td>
            <td style="border: 1px none black;"><p><b>Email:</b>info@baabtra.com <br><b>Phone:</b> +91-8592 058 444</p></td>
            <td style="border: 1px none black;"><p><b>Address:</b><br>5 <sup>th</sup>Floor, CaFIT Square, <br>Hi lite Business Park, Kozhikode</p></td>
        </tr>
        </table>
          

    </div>
    
</body>
</html>